JSQuiz-main/jsquiz/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('quiz.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

JSQuiz-main/quiz/urls.py
from django.conf.urls import url
from . import views

app_name = 'quiz'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^user-home$', views.user_home, name='user_home'),
    url(r'^play/$', views.play, name='play'),
    url(r'^leaderboard/$', views.leaderboard, name='leaderboard'),
    url(r'^submission-result/(?P<attempted_question_pk>\d+)/', views.submission_result, name='submission_result'),
    url(r'^login/', views.login_view, name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^register/', views.register, name='register'),

]

JSQuiz-main/quiz/models.py
import random
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from model_utils.models import TimeStampedModel


class Question(TimeStampedModel):
    ALLOWED_NUMBER_OF_CORRECT_CHOICES = 1

    html = models.TextField(_('Question Text'))
    is_published = models.BooleanField(_('Has been published?'), default=False, null=False)
    maximum_marks = models.DecimalField(_('Maximum Marks'), default=4, decimal_places=2, max_digits=6)

    def __str__(self):
        return self.html


class Choice(TimeStampedModel):
    MAX_CHOICES_COUNT = 4

    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    is_correct = models.BooleanField(_('Is this answer correct?'), default=False, null=False)
    html = models.TextField(_('Choice Text'))

    def __str__(self):
        return self.html


class QuizProfile(TimeStampedModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    total_score = models.DecimalField(_('Total Score'), default=0, decimal_places=2, max_digits=10)


    def get_new_question(self):
        used_questions_pk = AttemptedQuestion.objects.filter(quiz_profile=self).values_list('question__pk', flat=True)
        remaining_questions = Question.objects.exclude(pk__in=used_questions_pk)
        if not remaining_questions.exists():
            return
        return random.choice(remaining_questions)

    def create_attempt(self, question):
        attempted_question = AttemptedQuestion(question=question, quiz_profile=self)
        attempted_question.save()

    def evaluate_attempt(self, attempted_question, selected_choice):
        if attempted_question.question_id != selected_choice.question_id:
            return

        attempted_question.selected_choice = selected_choice
        if selected_choice.is_correct is True:
            attempted_question.is_correct = True
            attempted_question.marks_obtained = attempted_question.question.maximum_marks

        attempted_question.save()
        self.update_score()

    def update_score(self):
        marks_sum = self.attempts.filter(is_correct=True).aggregate(
            models.Sum('marks_obtained'))['marks_obtained__sum']
        self.total_score = marks_sum or 0
        self.save()

    def __str__(self):
        return f'<QuizProfile: user={self.user}>'


class AttemptedQuestion(TimeStampedModel):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    quiz_profile = models.ForeignKey(QuizProfile, on_delete=models.CASCADE, related_name='attempts')
    selected_choice = models.ForeignKey(Choice, on_delete=models.CASCADE, null=True)
    is_correct = models.BooleanField(_('Was this attempt correct?'), default=False, null=False)
    marks_obtained = models.DecimalField(_('Marks Obtained'), default=0, decimal_places=2, max_digits=6)

    def get_absolute_url(self):
        return f'/submission-result/{self.pk}/'

JSQuiz-main/quiz/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, get_user_model
from django.utils.translation import gettext as _
from .models import Question, Choice, QuizProfile


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['html', 'is_published']
        widgets = {
            'html': forms.Textarea(attrs={'rows': 3, 'cols': 80}),
        }


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['html', 'is_correct']
        widgets = {
            'html': forms.Textarea(attrs={'rows': 2, 'cols': 80}),
        }


class ChoiceInlineFormset(forms.BaseInlineFormSet):
    def clean(self):
        super(ChoiceInlineFormset, self).clean()

        correct_choices_count = 0
        for form in self.forms:
            if not form.is_valid():
                return

            if form.cleaned_data and form.cleaned_data.get('is_correct') is True:
                correct_choices_count += 1

        try:
            assert correct_choices_count == Question.ALLOWED_NUMBER_OF_CORRECT_CHOICES
        except AssertionError:
            raise forms.ValidationError(_('Exactly one correct choice is allowed.'))


User = get_user_model()


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exists")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect password")
            if not user.is_active:
                raise forms.ValidationError("This user is not active")
        return super(UserLoginForm, self).clean(*args, **kwargs)


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

JSQuiz-main/quiz/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from .models import QuizProfile, Question, AttemptedQuestion
from .forms import UserLoginForm, RegistrationForm
from  django.contrib import messages


def home(request):
    context = {}
    return render(request, 'quiz/home.html', context=context)


@login_required()
def user_home(request):
    context = {}
    return render(request, 'quiz/user_home.html', context=context)


def leaderboard(request):

    top_quiz_profiles = QuizProfile.objects.order_by('-total_score')[:500]
    total_count = top_quiz_profiles.count()
    context = {
        'top_quiz_profiles': top_quiz_profiles,
        'total_count': total_count,
    }
    return render(request, 'quiz/leaderboard.html', context=context)


@login_required()
def play(request):
    quiz_profile, created = QuizProfile.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        question_pk = request.POST.get('question_pk')

        attempted_question = quiz_profile.attempts.select_related('question').get(question__pk=question_pk)

        choice_pk = request.POST.get('choice_pk')

        try:
            selected_choice = attempted_question.question.choices.get(pk=choice_pk)
        except ObjectDoesNotExist:
            raise Http404

        quiz_profile.evaluate_attempt(attempted_question, selected_choice)

        return redirect(attempted_question)

    else:
        question = quiz_profile.get_new_question()
        if question is not None:
            quiz_profile.create_attempt(question)

        context = {
            'question': question,
        }

        return render(request, 'quiz/play.html', context=context)


@login_required()
def submission_result(request, attempted_question_pk):
    attempted_question = get_object_or_404(AttemptedQuestion, pk=attempted_question_pk)
    context = {
        'attempted_question': attempted_question,
    }

    return render(request, 'quiz/submission_result.html', context=context)


def login_view(request):
    title = "Login"
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('/user-home')
    return render(request, 'quiz/login.html', {"form": form, "title": title})


def register(request):
    title = "Create account"
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'You have Successfully Registered')
            #return redirect('/login')
    else:
        form = RegistrationForm()

    context = {'form': form, 'title': title}
    return render(request, 'quiz/registration.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('/')


def error_404(request):
    data = {}
    return render(request, 'quiz/error_404.html', data)


def error_500(request):
    data = {}
    return render(request, 'quiz/error_500.html', data)

JSQuiz-main/templates/quiz/error_404.html
{% extends 'base.html' %}
{% block title %} Let's Quiz | Page does not exists {% endblock title %}
{% block content %}
	<div class="container">
		<div class="alert alert-danger text-center" role="alert">
	          <h4 class="alert-heading">Error 404: Page not found</h4>
	          <p>The page you are looking does not exists. <a href="{% url 'quiz:home' %}" class="alert-link">Go back to homepage</a></p>
        </div>
    </div>

{% endblock content %}

JSQuiz-main/templates/quiz/error_500.html
{% extends 'base.html' %}
{% block title %} Let's Quiz | Internal Server Error {% endblock title %}
{% block content %}
	<div class="container">
		<div class="alert alert-danger text-center" role="alert">
	          <h4 class="alert-heading">Internal Server Error</h4>
	          <p>There is some error in internal server, we will be back soon.</p>
        </div>
    </div>

{% endblock content %}

JSQuiz-main/templates/quiz/leaderboard.html
{% extends 'base.html' %}
{% block title %} Let's Quiz | Leaderboard {% endblock title %}
{% block content %}
<div class="container">
    <br>
    <br>
    <br>
    <br>
    <br>
    <h1 class="text-center my-4"><span class="badge badge-info"><i class="fa fa-trophy" aria-hidden="true"></i> TOP {{ total_count }} PLAYERS <i class="fa fa-trophy" aria-hidden="true"></i></span></h1>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Position</th>
                <th>Username</th>
                <th>Score</th>
            </tr>
        </thead>
        <tbody>
            {% for quiz_profile in top_quiz_profiles %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ quiz_profile.user.username }}</td>
                <td>{{ quiz_profile.total_score }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

JSQuiz-main/templates/quiz/login.html
{% load static %}


<html>

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>JSQuiz | SignIn</title>
    <link rel="shortcut icon" href="{%static 'assets/img/title.png'%}" type="image/png">
    <meta content="" name="descriptison">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{%static 'assets/img/favicon.png'%}" rel="icon">
    <link href="{%static 'assets/img/apple-touch-icon.png'%}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{%static 'assets/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{%static 'assets/vendor/icofont/icofont.min.css'%}" rel="stylesheet">
    <link href="{%static 'assets/vendor/boxicons/css/boxicons.min.css'%}" rel="stylesheet">
    <link href="{%static 'assets/vendor/remixicon/remixicon.css'%}" rel="stylesheet">
    <link href="{%static 'assets/vendor/venobox/venobox.css'%}" rel="stylesheet">
    <link href="{%static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css'%}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{%static 'assets/css/style.css' %}" rel="stylesheet">
    <link href="{%static 'assets/css/form.css' %}" rel="stylesheet">
</head>


<body>

<header id="header1" class="fixed-top ">
    <div class="container-fluid">

        <div class="row justify-content-center">
            <div class="col-xl-9 d-flex align-items-center justify-content-between">
                <h1 class="logo"><img src="{%static 'assets/img/bitlogo.png' %}" style="width: 35px"><img
                        src="{%static 'assets/img/clogo.png' %}" style="width: 40px"></h1>
                <!-- Uncomment below if you prefer to use an image logo -->
                <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

                <nav class="nav-menu d-none d-lg-block">
            <ul>
              <!-- <li class="active"><a href="index.html">Home</a></li> -->
<!--              <li><a href="{% url 'quiz:home' %}">Home</a></li>-->
<!--              <li><a href="{% url 'quiz:leaderboard' %}">LeaderBoard</a></li>-->
              {% if not request.user.is_active %}
              <li><a href="{% url 'quiz:leaderboard' %}" ><i class="fas fa-book-reader" aria-hidden="true"></i> LeaderBoard</a></li>
              <li><a href="{% url 'quiz:login' %}" ><i class="fa fa-sign-in" aria-hidden="true"></i>LogIn</a></li>
              {% else %}
              <li><a href="{% url 'quiz:play' %}" >Welcome, {{ request.user.username }} | </a></li>
              <li><a href="{% url 'quiz:play' %}" ><i class="fas fa-play" aria-hidden="true"></i> Lets Play</a></li>
              <li><a href="{% url 'quiz:logout' %}" ><i class="fa fa-sign-in" aria-hidden="true"></i> Logout</a></li>
              {% endif %}


            </ul>
          </nav><!-- .nav-menu -->
            </div>
        </div>

    </div>
</header><!-- End Header -->
<div class="container">

    {% if not request.user.is_active %}

    <div class="container">
        <br>
        <br>
        <br>
        <form method="post" action="" id="login-form" class="login-form" autocomplete="off" role="main">
            <figure aria-hidden="true">
                <div class="person-body"></div>
                <div class="neck skin"></div>
                <div class="head skin">
                    <div class="eyes"></div>
                    <div class="mouth"></div>
                </div>
                <div class="hair"></div>
                <div class="ears"></div>
                <div class="shirt-1"></div>
                <div class="shirt-2"></div>
            </figure>
            <h1 class="a11y-hidden">Login Form</h1>
            {% csrf_token %}
            <div>
                <label class="label-email">
                    <input type="text" class="text" name="username" id="username" placeholder="username" tabindex="1" required/>
                    <span class="required">Username</span>
                </label>
            </div>
            <input type="checkbox" name="show-password" class="show-password a11y-hidden" id="show-password"
                   tabindex="3"/>
            <div>
                <label class="label-password">
                    <input type="text" class="text" name="password" id="password" placeholder="Password" tabindex="2" required/>
                    <span class="required">Password</span>
                </label>
            </div>
<!--            {{form }}-->
            <input class="get-started-form scrollto" type="submit" value="Log In"/>
            <br>
            <div class="text-center">
                <p>or ...</p>
                <a href="{% url 'quiz:register' %}" class="get-started-form scrollto">Create account</a>
            </div>
<!--            <figure aria-hidden="true">-->
<!--                <div class="person-body"></div>-->
<!--                <div class="neck skin"></div>-->
<!--                <div class="head skin">-->
<!--                    <div class="eyes"></div>-->
<!--                    <div class="mouth"></div>-->
<!--                </div>-->
<!--                <div class="hair"></div>-->
<!--                <div class="ears"></div>-->
<!--                <div class="shirt-1"></div>-->
<!--                <div class="shirt-2"></div>-->
<!--            </figure>-->
        </form>
    </div>
    <div>
        {% else %}

        <section id="section-jumbotron"
                 class="jumbotron jumbotron-fluid d-flex justify-content-center align-items-center">
            <div class="container text-center">
                <h1 class="display-1 text-info">Let's Quiz</h1>
                <p class="display-4 d-none d-sm-block">Test your skills and become a master.</p>
                <p class="lead">We organize quizzes on various topics.</p>
                <a href="{% url 'quiz:play' %}" class="btn btn-lg btn-info mt-1">Let's play</a>
                <a href="{% url 'quiz:leaderboard' %}" class="btn btn-lg btn-info mt-1">Leaderboard</a>
            </div>
        </section>

        {% endif %}

        <!-- Vendor JS Files -->
        <script src="{%static 'assets/vendor/jquery/jquery.min.js'%}"></script>
        <script src="{%static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
        <script src="{%static 'assets/vendor/jquery.easing/jquery.easing.min.js'%}"></script>
        <script src="{%static 'assets/vendor/php-email-form/validate.js'%}"></script>
        <script src="{%static 'assets/vendor/waypoints/jquery.waypoints.min.js'%}"></script>
        <script src="{%static 'assets/vendor/counterup/counterup.min.js'%}"></script>
        <script src="{%static 'assets/vendor/isotope-layout/isotope.pkgd.min.js'%}"></script>
        <script src="{%static 'assets/vendor/venobox/venobox.min.js'%}"></script>
        <script src="{%static 'assets/vendor/owl.carousel/owl.carousel.min.js'%}"></script>

        <!-- Template Main JS File -->
        <script src="https://kit.fontawesome.com/23cd0e260d.js" crossorigin="anonymous"></script>
        <script src="{%static 'assets/js/main.js'%}"></script>
        <script src="{%static 'assets/js/jquery.min.js'%}"></script>
        <script src="{%static 'assets/bootstrap/js/bootstrap.min.js'%}"></script>
    </div>
</div>
</body>
</html>

JSQuiz-main/templates/quiz/registration.html
{% load static %}

<html>

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>JSQuiz | SignIn</title>
    <link rel="shortcut icon" href="{% static 'assets/img/title.png' %}" type="image/png">
    <meta content="" name="descriptison">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/form.css' %}" rel="stylesheet">
</head>


<body>

<header id="header1" class="fixed-top ">
    <div class="container-fluid">

        <div class="row justify-content-center">
            <div class="col-xl-9 d-flex align-items-center justify-content-between">
                <h1 class="logo"><img src="{% static 'assets/img/bitlogo.png' %}" style="width: 35px"><img
                        src="{% static 'assets/img/clogo.png' %}" style="width: 40px"></h1>
                <!-- Uncomment below if you prefer to use an image logo -->
                <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

                <nav class="nav-menu d-none d-lg-block">
            <ul>
              <!-- <li class="active"><a href="index.html">Home</a></li> -->
<!--              <li><a href="{% url 'quiz:home' %}">Home</a></li>-->
<!--              <li><a href="{% url 'quiz:leaderboard' %}">LeaderBoard</a></li>-->
              {% if not request.user.is_active %}
              <li><a href="{% url 'quiz:leaderboard' %}" ><i class="fas fa-book-reader" aria-hidden="true"></i> LeaderBoard</a></li>
              <li><a href="{% url 'quiz:login' %}" ><i class="fa fa-sign-in" aria-hidden="true"></i>LogIn</a></li>
              {% else %}
              <li><a href="{% url 'quiz:play' %}" >Welcome, {{ request.user.username }} | </a></li>
              <li><a href="{% url 'quiz:play' %}" ><i class="fas fa-play" aria-hidden="true"></i> Lets Play</a></li>
              <li><a href="{% url 'quiz:logout' %}" ><i class="fa fa-sign-in" aria-hidden="true"></i> Logout</a></li>
              {% endif %}


            </ul>
          </nav><!-- .nav-menu -->
            </div>
        </div>

    </div>
</header><!-- End Header -->
<div class="container">
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    {% if not request.user.is_active %}
    <form method="POST" action="" id="login-form" class="login-form" autocomplete="off" role="main">
        {% csrf_token %}
        <h1 class="a11y-hidden">Login Form</h1>
        <div>
            <label>
                <span class="required">Username</span>
                <input type="text" class="text" name="username" id="username" placeholder="Username" tabindex="1" required/>
                <p style="font-size: 10px; margin-bottom:.2rem;">Required. 150 characters or fewer.</p>
                <p style="font-size: 10px; margin-bottom:.2rem;">Letters, digits and @/./+/-/_ only.</p>
            </label>
        </div>
        <div>
            <label class="label-email">
                <span class="required">Email</span>
                <input type="email" class="text" name="email" id="email" placeholder="Email" tabindex="1" required/>
            </label>
        </div>
        <div>
            <label class="label-email">
                <span class="required">First name</span>
                <input type="text" class="text" name="first_name" placeholder="Firstname" id="first_name" tabindex="1" required/>
            </label>
        </div>
        <div>
            <label class="label-email">
                <span class="required">Last name</span>
                <input type="text" class="text" name="last_name" placeholder="Lastname"  id="last_name" tabindex="1" required/>
            </label>
        </div>
        <div>
            <label class="label-password">
                <span class="required">Password</span>
                <input type="text" class="text" name="password1" placeholder="Password" id="password1" tabindex="2" required/>
                <p style="font-size: 10px; margin-bottom:.2rem;">Your password can't be too similar to your</p>
                <p style="font-size: 10px; margin-bottom:.2rem;">other personal information.</p>
                <p style="font-size: 10px; margin-bottom:.2rem;">Your password must contain at least 8 characters.</p>
                <p style="font-size: 10px; margin-bottom:.2rem;">Your password can't be a commonly used password.</p>
                <p style="font-size: 10px; margin-bottom:.2rem;">Your password can't be entirely numeric.</p>
            </label>
        </div>
        <div>
            <label class="label-password">
                <span class="required">Password confirmation</span>
                <input type="text" class="text" name="password2" placeholder="Password" id="password2" tabindex="2" required/>
            </label>
        </div>
        <input class="get-started-form scrollto" type="submit" value="Create account"/>
        <br>
        <div class="text-center">
            <p style="font-size: 10px; margin-bottom:.2rem;">or ...</p>
            <a href="{% url 'quiz:login' %}" class="get-started-form scrollto"><i class="fa fa-sign-in"
                                                                                     aria-hidden="true"></i> Log in</a>
        </div>
        <!-- <div class="email">
          <a href="#">Forgot password?</a>
        </div> -->
    </form>
    {% else %}
            <h1 class="display-1 text-info">JS Quiz</h1>
    <h6 class="display-1 text-info">Welcome, {{ request.user.username }} | </h6>
        <p class="display-4 d-none d-sm-block">Test your skills and become a master.</p>
        <p class="lead">We organize quizzes on various topics.</p>
        <a href="{% url 'quiz:play' %}" class="btn btn-lg btn-info mt-1">Let's play</a>
        <a href="{% url 'quiz:leaderboard' %}" class="btn btn-lg btn-info mt-1">Leaderboard</a>
    {% endif %}
</div>
<div>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'assets/vendor/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="https://kit.fontawesome.com/23cd0e260d.js" crossorigin="anonymous"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
</div>
</body>
</html>

JSQuiz-main/templates/quiz/submission_result.html
{% extends 'base.html' %}
{% block title %} Let's Quiz | Submission Result {% endblock title %}
{% block content %}
<div class="container">
	<br>
    <br>
    <br>
    <br>
    <br>
	<div class="jumbotron my-4">

	   	<h3>{{ attempted_question.question.html|safe }}</h3>

		<p>
		    <strong>Your answer: </strong>
		    {{ attempted_question.selected_choice.html|safe }}
		</p>

		<h4>Yay...Next Question</h4>
<!--		{% if attempted_question.selected_choice.is_correct %}-->
<!--		<h4 class="text-success">Yayy!! Your answer is correct. High Five! 🙌</h4>-->
<!--		{% else %}-->
<!--		<h4 class="text-danger">Your answer is incorrect 😟</h4>-->
<!--		{% endif %}-->
		<br>
		<a class="get-started-btn scrollto" href="{% url 'quiz:play' %}">Show next question</a>
	</div>
</div>

{% endblock content %}